/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dbdad6',
        'primary-fixed-dim': '#b4ceaf',
        'secondary-fixed': '#ffddba',
        'error': '#ba1a1a',
        'surface-container-high': '#eae8e4',
        'inverse-on-surface': '#f2f0ed',
        'outline-variant': '#c3c8bf',
        'surface-tint': '#4d644b',
        'on-surface-variant': '#434841',
        'on-surface': '#1b1c1a',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#0b200c',
        'tertiary-container': '#e68570',
        'outline': '#737971',
        'tertiary-fixed': '#ffdad3',
        'inverse-surface': '#30312e',
        'surface-container-low': '#f5f3ef',
        'background': '#fbf9f5',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#efeeea',
        'primary-container': '#8da689',
        'surface': '#fbf9f5',
        'inverse-primary': '#b4ceaf',
        'secondary': '#85530d',
        'on-tertiary-fixed': '#3d0600',
        'surface-variant': '#e4e2de',
        'secondary-container': '#ffbc6f',
        'surface-bright': '#fbf9f5',
        'tertiary': '#964735',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        'on-secondary-fixed-variant': '#673d00',
        'tertiary-fixed-dim': '#ffb4a4',
        'on-background': '#1b1c1a',
        'on-primary-container': '#263b25',
        'on-tertiary-container': '#632012',
        'primary-fixed': '#cfeaca',
        'on-secondary-container': '#794a02',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#fcb96d',
        'primary': '#4d644b',
        'surface-container-highest': '#e4e2de',
        'on-primary-fixed-variant': '#364c35',
        'on-tertiary-fixed-variant': '#783020',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#2b1700',
      },
      borderRadius: {
        DEFAULT: '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
        '12': '12px',
        '16': '16px',
        '50': '50px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Be Vietnam Pro"', 'sans-serif'],
        label: ['"Be Vietnam Pro"', 'sans-serif'],
      },
      boxShadow: {
        'ambient': '0 8px 40px rgba(67,72,65,0.06)',
        'card': '0 4px 20px rgba(67,72,65,0.04)',
        'float': '0 12px 60px rgba(67,72,65,0.10)',
        'nav': '0 -4px 40px rgba(67,72,65,0.05)',
      }
    },
  },
  plugins: [],
}
